import "./globals.css"
import type { Metadata } from "next"
import { Darker_Grotesque } from "next/font/google"
import { ScrollProvider } from "@/context/ScrollProvider"

const darkerGrotesque = Darker_Grotesque({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={darkerGrotesque.className}>
        <ScrollProvider>
          <main className="flex min-h-screen flex-col h-full w-full">
            {children}
          </main>
        </ScrollProvider>
      </body>
    </html>
  )
}
